<?php
use Drupal\Core\Form\FormStateInterface;


function report_download_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
}

function report_download_preprocess_page(&$variables) {
 $reportform = \Drupal::formBuilder()->getForm('Drupal\report_download\Form\ReportSearchData');
 $variables['report_form']=$reportform;
 $companyreportform = \Drupal::formBuilder()->getForm('Drupal\report_download\Form\CompanyReportSearchData');
 $variables['company_report_form']=$companyreportform;
}