<?php

use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_user_login().
 */
function oxfam_user_login(UserInterface $account)
{
  $first_name = $account->get('field_first_name')->value;
  $last_name = $account->get('field_last_name')->value;
  $mobile = $account->get('field_mobile_number')->value;
  $user = $account->getDisplayName();
  $email = $account->getEmail();
  if ($account->getEmail() == 'devenderdagar@gmail.com') {
    $redirect = new RedirectResponse(Url::fromUserInput('/form/registration?first_name='.$first_name.'&last_name='.$last_name.'&username='.$user.'&email_address='.$email.'&mobile_number='.$mobile)->toString());
  } else {
    $redirect = new RedirectResponse(Url::fromUserInput('/form/registration?first_name='.$first_name.'&last_name='.$last_name.'&username='.$user.'&email_address='.$email.'&mobile_number='.$mobile)->toString());
  }
  $redirect->send();
}

/**
 * Implements hook_user_insert().
 */
function oxfam_user_insert(Drupal\Core\Entity\EntityInterface $entity)
{
  $webform_id = 'registration';
  $webform = Webform::load($webform_id);
  $values = [
    'webform_id' => $webform->id(),
    'data' => [
      'first_name' => $entity->get('field_first_name')->value,
      'last_name' => $entity->get('field_last_name')->value,
      'mobile_number' => $entity->get('field_mobile_number')->value,
      'username' => $entity->getUsername(),
      'email_address' => $entity->getEmail()
    ],
    'uid' => $entity->id()
  ];
  $webform_submission = WebformSubmission::create($values);
  $webform_submission->save();
}
